name: Deploy ASP.NET API to Railway

on:
  push:
    branches:
      - main
    paths:
      - "MyStockApi/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        working-directory: MyStockApi
        run: dotnet restore

      - name: Build project
        working-directory: MyStockApi
        run: dotnet build -c Release --no-restore

      - name: Publish project
        working-directory: MyStockApi
        run: dotnet publish -c Release -o out --no-build

      - name: Trigger Railway Deploy
        run: |
          curl -X POST ${{ secrets.RAILWAY_DEPLOY_HOOK }}